### ISSUE TITLE
Make ImageMagick available to docker container

### ISSUE THREAD

**Issue by chirale** [bwdutton/gallery3-docker#4]
For a path issue, now ImageMagick is installed but not available to Gallery3. Adding these symlinks fix the issue.

```WEB_CONTAINER=your-container-name && docker exec -it $WEB_CONTAINER bash
ln -sf /usr/bin/convert /usr/local/bin/convert && \
   ln -sf /usr/bin/convert-im6 /usr/local/bin/convert-im6 && \
   ln -sf /usr/bin/convert-im6.q16 /usr/local/bin/convert-im6.q16
```
So adding these after imagemagick installation will make IM available.

I've not yet done extensive tests, but result on Settings > Graphics is not greyed out anymore:
![Screenshot_2020-11-29 Gallery Admin Graphics settings](https://user-images.githubusercontent.com/2143851/100538679-8751bf80-3231-11eb-8def-45b0d4164a96.png)

The FLOSS project CollectiveAccess has addressed similar issues in the past, and the solution was to centralize paths on a conf file:
https://github.com/collectiveaccess/providence/blob/master/app/conf/external_applications.conf
https://docs.collectiveaccess.org/wiki/External_Application_Configuration

and giving each library a weight to sort by better-worst available (better always win, in gallery3 imagemagick will win to GD).

A file like this referencing the right paths on the image can be later copied using docker COPY to avoid using symlinks.

**Comment by bwdutton** [comment]
I set the PATH for PHP and all of the binaries are now found. The weird thing is on my install ImageMagick was selected by default but if I chose GD I couldn't go back to ImageMagick. Either way, it's fixed now:
https://github.com/bwdutton/gallery3-docker/commit/164b6bbfb6739d9d49f61b08a2443dbf02ead56c
