### ISSUE TITLE
Organize album - not functional 

### ISSUE THREAD

**Issue by pchevallier** [bwdutton/gallery3-docker#5]
While trying to move around some of the albums, I noticed that one option is not functioning correctly: "Organize album".

![Screen Shot 2020-11-30 at 2 42 38 PM](https://user-images.githubusercontent.com/20049529/100656187-4f727700-331a-11eb-9811-64429727deab.png)
When selected, a frame shows up but nothing else and checking on the console of my browser, I see the following error:

![Screen Shot 2020-11-30 at 2 45 14 PM](https://user-images.githubusercontent.com/20049529/100656400-ad9f5a00-331a-11eb-94d6-4fbbc38b6270.png)

"http://.../organize/frame/1:11"

**Comment by bwdutton** [comment]
I just made a fix for this, please do a docker pull. This was the fix:
https://github.com/bwdutton/gallery3-docker/commit/0dab57dd77ff8b2eba907294d1775d0c8ac46157
