### ISSUE TITLE
Trying to get mail working

### ISSUE THREAD

**Issue by davep47** [bwdutton/gallery3-docker#8]
I am trying to get mail working either with the built in or PHPMailer and not having any luck.

The files under modules/phpmailer did not seem to be complete and were missing the admin page.
I downloaded the latest version and unzipped them after installing PHPMailer but I am still getting an error.
I installed PHPMailer via: 
composer require phpmailer/phpmailer
I have seen the notes to make sure to update the location of class.phpmailer.php but can't find the file.
Thanks
`Exception [ 0 ]:
@todo SEND_MAIL_FAILED
MODPATH/phpmailer/libraries/Sendmail.php[ 90 ]

85    // The docs say headers should be separated by \r\n, but occasionaly that doesn't work and you
86    // need to use a single \n.  This can be set in config/sendmail.php
87    $headers = implode($this->header_separator, $headers);
88    $message = wordwrap($this->message, $this->line_length, "\n");
89    if (!$this->mail($to, $this->subject, $message, $headers)) {
90      throw new Exception("@todo SEND_MAIL_FAILED");
91    }
92    return $this;
93  }
94
95  public function mail($to, $subject, $message, $headers) {
MODPATH/register/helpers/register.php[ 136 ] » Sendmail_Core->send()

MODPATH/register/helpers/register.php[ 55 ] » register_Core::_sendemail()

MODPATH/register/helpers/register.php[ 123 ] » register_Core::send_user_created_confirmation()

MODPATH/register/controllers/admin_register.php[ 77 ] » register_Core::create_new_user()

MODPATH/gallery/controllers/admin.php[ 62 ] » Admin_register_Controller->activate()

{PHP internal call} » Admin_Controller->__call()

SYSPATH/core/Kohana.php[ 331 ] » ReflectionMethod->invokeArgs()

SYSPATH/core/Event.php[ 208 ] » Kohana_Core::instance()

APPPATH/Bootstrap.php[ 67 ] » Event_Core::run()

DOCROOT/index.php[ 123 ] » require( arguments )
`

**Comment by bwdutton** [comment]
If you want to copy the updated files into your installation you can:
https://github.com/bwdutton/gallery3/tree/master/modules/phpmailer
Otherwise I'll try to get an updated release out next week.

**Comment by davep47** [comment]
Thanks.
I downloaded it and reloaded, ran composer install in /var/www and it still
doesn't work.
I am testing it with user activation. Before it gave an error but now it
just spins.

**Comment by bwdutton** [comment]
Sorry for the long delay, I just posted an updated docker build. Please give that a try and let me know how it goes.

**Comment by bwdutton** [comment]
Closing, no reply
